on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *' # every twenty minutes
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data from the API endpoint
      run: |-
        curl -s "https://www.change.org/api-proxy/-/discover_feed?is_homepage=true&initial_request=true&ip_city=London&ip_country_code=GB&ip_postal_code=SW9&ip_region=ENG&locale=en-GB&page=0&recommendation_filter=default_GB&recommendable_locale=true&show_subscriptions=false" | jq '.data.context.articles' > headlines.json
    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
